### PR TITLE
Adding new events, and a few tests to match.

### PR DESCRIPTION
**Pull request by AnmAtAnm**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/339)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
PTAL @roboerikg 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/339#-:-KM6YgEjM2DmYWvVrbAd:1290518790)*

**Comment by RoboErikG** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java, line 67 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/339#-KM6Z2YtcMDVKVH7wFwC:-KM6Z2YtcMDVKVH7wFwD:-1786784897) ([raw file](https://github.com/google/blockly-android/blob/02e6fb0e3ad83b5b352a54ad9a94d34ddd2ab98b/blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java#L67)):*
> ```Java
>     protected CodeGenerationRequest.CodeGeneratorCallback mCodeGeneratorCallback =
>             new LoggingCodeGeneratorCallback(this, TAG);
>     protected LogAllEventsListener mEventsListener = new LogAllEventsListener("BlocklyEvents");
> ```

s/Listener/Callback

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 654 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/339#-KM6ZN-djzT3FTBdbQMV:-KM6ZN-djzT3FTBdbQMW:2140133894) ([raw file](https://github.com/google/blockly-android/blob/02e6fb0e3ad83b5b352a54ad9a94d34ddd2ab98b/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L654)):*
> ```Java
>         checkPendingEventsEmpty();
> 
>         boolean rootFoundAndRemoved = removeRootBlock(block, true);
> ```

Why doesn't this use the impl pattern that the other public methods use?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 896 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/339#-KM6ZfbUC1lexEye2rUH:-KM6ZfbV8blPtw9-CQX3:477761284) ([raw file](https://github.com/google/blockly-android/blob/02e6fb0e3ad83b5b352a54ad9a94d34ddd2ab98b/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L896)):*
> ```Java
>             } else {
>                 // Store the original location of the remainder.
>                 remainderMove = new BlocklyEvent.MoveEvent(mWorkspace, remainderBlock);
> ```

You never call remainderMove.recordNew() or addPendingEvent(remainderMove)

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 1133 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/339#-KM6_-2I_fEKrGg1P9mi:-KM6_-2I_fEKrGg1P9mj:842745899) ([raw file](https://github.com/google/blockly-android/blob/02e6fb0e3ad83b5b352a54ad9a94d34ddd2ab98b/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L1133)):*
> ```Java
>         }
> 
>         firePendingEvents();
> ```

remove firePendingEvents.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/339)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java, line 67 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/339#-KM6Z2YtcMDVKVH7wFwC:-KM6aNewhMpsp5ZEJrlV:-499146009) ([raw file](https://github.com/google/blockly-android/blob/02e6fb0e3ad83b5b352a54ad9a94d34ddd2ab98b/blocklydemo/src/main/java/com/google/blockly/android/demo/DevTestsActivity.java#L67)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary>
> s/Listener/Callback
</details>
Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 654 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/339#-KM6ZN-djzT3FTBdbQMV:-KM6_uwMeATyAB-4UEec:-956549939) ([raw file](https://github.com/google/blockly-android/blob/02e6fb0e3ad83b5b352a54ad9a94d34ddd2ab98b/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L654)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary>
> Why doesn't this use the impl pattern that the other public methods use?
</details>
Nothing else would need to call trashRootBlockImpl().

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 896 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/339#-KM6ZfbUC1lexEye2rUH:-KM6g8WhWUUvMtnV7jw8:-499146009) ([raw file](https://github.com/google/blockly-android/blob/02e6fb0e3ad83b5b352a54ad9a94d34ddd2ab98b/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L896)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary>
> You never call remainderMove.recordNew() or addPendingEvent(remainderMove)
</details>
Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 1133 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/339#-KM6_-2I_fEKrGg1P9mi:-KM6a_0-aZU6P4LxGAQw:-1171100784) ([raw file](https://github.com/google/blockly-android/blob/02e6fb0e3ad83b5b352a54ad9a94d34ddd2ab98b/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L1133)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary>
> remove firePendingEvents.
</details>
Whoops. Came in from merge.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/339)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/339#-:-KM6kifZJ7xU_5F6vyiH:1417088721)*

**Pull request merged**
