### PR TITLE
625 Add checkstyle and run it from travis

### LINKED ISSUE #625: Add checkstyle to Gradle

### PR DESCRIPTION
**Pull request by ChrisCanCompute**
Fixes #625.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/697)

### CODE REVIEW

**Comment by ChrisCanCompute** [comment]
I could also add in maxAllowedViolations to prevent future commits making things worse (without increasing the limit, which will help flag when it happens).
Thoughts?

**Comment by AnmAtAnm** [comment]
Setting `maxAllowedViolations` to 92 (the results from this travis build) sounds like a good idea.

**Comment by ChrisCanCompute** [comment]
Awesome! I'll update it on Monday.

**Comment by ChrisCanCompute** [comment]
It looks like `maxAllowedViolations` is now `maxErrors` and `maxWarnings` (see https://github.com/gradle/gradle/issues/881) but I can't seem to get them working (I set them both to 1 and the build is still passing).

Happy for you to have a look to see if you can get it working. Otherwise, it might be beneficial this as is, and update #625 to cover adding limits in.

**Comment by AnmAtAnm** [comment]
Reading that other issue thread:

> To rephrase what's still missing: You want a warning log message if there were any warnings or errors detected.

Sounds like the behavior you are seeing is working as currently expected (but not desired).

I'm not going to have time to dig into this. Let me know if you want me to pull in what you have, or keep working on it.

**Comment by ChrisCanCompute** [comment]
Can you pull this in as is?
(I'm keen to address some of the items it's raised)
I might also have a look at gradle and see if I can help fix the issue there (that I've linked to here).

**Pull request merged**
