### PR TITLE
Changes to allow hats per block type

### PR DESCRIPTION
**Pull request by jorgebonafe**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/660)

### CODE REVIEW

**Comment by jorgebonafe** [comment]
I signed it!

2017-09-20 20:30 GMT-03:00 googlebot <notifications@github.com>:

**Comment by RoboErikG** [comment]
Hi Jorge,

Thanks for the PR. Because of all the unrelated changes we won't be able to merge it, but we'll take a look at the relevant pieces. If you're feeling ambitious about learning git you could try creating a separate branch and [cherry-picking](http://think-like-a-git.net/sections/rebase-from-the-ground-up/cherry-picking-explained.html) just the hat related changes.

**Comment by jorgebonafe** [comment]
Ok, if I have some time I'll might take a look at that tomorrow.

2017-09-20 20:45 GMT-03:00 RoboErikG <notifications@github.com>:

**Comment by jorgebonafe** [comment]
Yeah, I'm afraid to mess too much with this and screw up my Git somehow.
But my changes to hats are on these two commits. Everything I changed for
the hat features are here, and there are no unrelated changes on them
either. They are pretty simple, really.

https://github.com/jorgebonafe/blockly-android/commit/1e618c7bbf61d2bed3284794ec35a701fe6756d4
https://github.com/jorgebonafe/blockly-android/commit/45238e287dccacaba4412767ed8fed684c656c6b




2017-09-20 20:53 GMT-03:00 Jorge Bonafé <jorgebonafe@gmail.com>:

> Ok, if I have some time I'll might take a look at that tomorrow.
>
> 2017-09-20 20:45 GMT-03:00 RoboErikG <notifications@github.com>:
>
>> Hi Jorge,
>>
>> Thanks for the PR. Because of all the unrelated changes we won't be able
>> to merge it, but we'll take a look at the relevant pieces. If you're
>> feeling ambitious about learning git you could try creating a separate
>> branch and cherry-picking
>> <http://think-like-a-git.net/sections/rebase-from-the-ground-up/cherry-picking-explained.html>
>> just the hat related changes.
>>
>

**Comment by AnmAtAnm** [comment]
With respect to preserving your existing work, you just need to make sure you are working in a separate branch (or even safer, a separate repo clone). No worries if you prefer to leave it to us.  We can do that, but it will take longer.

Regardless, thanks for the code.

**Pull request closed without merging**
