### PR TITLE
Remove variable init from demos

### PR DESCRIPTION
**Pull request by RoboErikG**
Variables no longer need to be initialized in the activity. Remove the inits from demos.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/539)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
More in TurtleActivity, StylesActivity, SplitActivity?
DevTestsActivity might be the one place worth keeping.

**Comment by RoboErikG** [comment]
I think it makes sense for the TurtleActivity to still set some variables ahead of time since they're very useful for the more interesting drawings. I could go either way on Styles and Split, so I'll remove those two.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/539#-:-Ke5CD3qmzkKlYt0iik4:b36krej)*

**Comment by RoboErikG** [comment]
Done.

**Comment by AnmAtAnm** [comment]
LGTM

**Pull request merged**
