### PR TITLE
Adding events to Block.setCollapsed(), .setComment(), .setDisabled(), .setInputsInline()

### PR DESCRIPTION
**Pull request by AnmAtAnm**
Triggering events during `Block.setCollapsed()`, `.setComment()`, `.setDisabled()`, `.setInputsInline()`.  This first implementation of events triggered from outside BlocklyController also tests the framework.

 * All blocks now maintain a reference to the BlocklyController associated with their BlockFactory, allowing them to call `.groupAndFireEvents(..)` and `.addPendingEvents(..)`.
 * Since threading in testing is becoming more important, moved relevant code to `BlocklyTestCase`. Now correctly using the instrumented main thread, instead of a new thread. Call `configureForUIThread()` to set up.
 * Adds `BlockContainer` interface to `Block` and `Workspace`. Not fully implemented, but gives the framework for event "workspace" ids outside the `Workspace` (toolbox blocks, trash blocks, etc). Event constructors params get this id from the block, right now. However, this is currently broken; all events have null for workspace id. See #567.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/568)

### CODE REVIEW

**Comment by RoboErikG** [comment]
Most of it looks good. As discussed, more efficient to make only workspaces/toolboxes be block containers and to set it on blocks when they are added/moved/removed between them.

---

Review status: 0 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Block.java, line 124 at r1](https://reviewable.io:443/reviews/google/blockly-android/568#-KhwmFdT2bBUgVMuR3FQ:-KhwmFdT2bBUgVMuR3FR:by333jm) ([raw file](https://github.com/google/blockly-android/blob/f8b3044e66b70409a865c17a554740d10ee9a977/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L124)):*
> ```Java
> 
>     /**
>      * @param factory The factory creating this block.
> ```

missing controller @param

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Block.java, line 526 at r1](https://reviewable.io:443/reviews/google/blockly-android/568#-KhwpTWyrzatX7cj9Zq1:-KhwpTWyrzatX7cj9Zq2:btmfpnl) ([raw file](https://github.com/google/blockly-android/blob/f8b3044e66b70409a865c17a554740d10ee9a977/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L526)):*
> ```Java
>     public void setInputsInline(final boolean inputsInline) {
>         // Mark modified state for next serialization.
>         mInputsInlineModified = true;
> ```

Should this be after the check to see if it changed?

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockContainer.java, line 8 at r1](https://reviewable.io:443/reviews/google/blockly-android/568#-Khwna5tw0_dLJfxV109:-Khwna5tw0_dLJfxV10A:b-fdmqvx) ([raw file](https://github.com/google/blockly-android/blob/f8b3044e66b70409a865c17a554740d10ee9a977/blocklylib-core/src/main/java/com/google/blockly/model/BlockContainer.java#L8)):*
> ```Java
> /**
>  * Interface for traversing block trees, including {@link Block}, {@link Workspace}, and eventually
>  * {@link BlocklyCategory} for the toolbox and trash.
> ```

As discussed, make only Workspaces and Categories implement and set on all blocks when moving between containers (via the controller).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/568#-:-KhwqEhwlmLeFp4SVaYG:b-s3g0a8)*

**Comment by AnmAtAnm** [comment]
PTAL @roboerikg 

---

Review status: 0 of 25 files reviewed at latest revision, 3 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Block.java, line 124 at r1](https://reviewable.io:443/reviews/google/blockly-android/568#-KhwmFdT2bBUgVMuR3FQ:-Khx7iyLADdyPYEElhZ9:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/f8b3044e66b70409a865c17a554740d10ee9a977/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L124)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

missing controller @param
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Block.java, line 526 at r1](https://reviewable.io:443/reviews/google/blockly-android/568#-KhwpTWyrzatX7cj9Zq1:-Khx76bl3WkWC25GVAkJ:b-y4mbbx) ([raw file](https://github.com/google/blockly-android/blob/f8b3044e66b70409a865c17a554740d10ee9a977/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L526)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Should this be after the check to see if it changed?
</blockquote></details>

If it is called, we need to assume it was intentional and counts as a modification, even if the underlying value does not change. Not doing this breaks the tests, correctly.

Clarified comment.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockContainer.java, line 8 at r1](https://reviewable.io:443/reviews/google/blockly-android/568#-Khwna5tw0_dLJfxV109:-Khx_u7emU4lidYYBad2:b-n19jkm) ([raw file](https://github.com/google/blockly-android/blob/f8b3044e66b70409a865c17a554740d10ee9a977/blocklylib-core/src/main/java/com/google/blockly/model/BlockContainer.java#L8)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

As discussed, make only Workspaces and Categories implement and set on all blocks when moving between containers (via the controller).
</blockquote></details>

Removed the interface, because it was down to just `getId()`. Now just setting/getting a string. Seems to work at least for the workspace but needs better testing (tracked in #567).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/568#-:-KhxcZtOvcMbvLNEM_dp:blccao6)*

**Comment by RoboErikG** [comment]
Review status: 0 of 25 files reviewed at latest revision, 7 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Block.java, line 1207 at r2](https://reviewable.io:443/reviews/google/blockly-android/568#-Khxf_KZk6j_5QBL0iuX:-Khxf_K_eMaatRTq8P8S:b-mpj43m) ([raw file](https://github.com/google/blockly-android/blob/91ef0bb71b8d6e984b38cc992f6a675a7251653b/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L1207)):*
> ```Java
>      * @param runnable Code to run.
>      */
>     private void groupAndMaybeFireEvents(Runnable runnable) {
> ```

Just a note, if mEventWorkspaceId ever gets modified on a different thread you could have a race condition. It should be fine unless someone is intentionally mucking with threads.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java, line 488 at r2](https://reviewable.io:443/reviews/google/blockly-android/568#-KhxgKDV4IiXDp5f7KzE:-KhxgKDW9Em8UP6Grwxh:b6n33nm) ([raw file](https://github.com/google/blockly-android/blob/91ef0bb71b8d6e984b38cc992f6a675a7251653b/blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java#L488)):*
> ```Java
>          */
>         public DeleteEvent(@NonNull String workspaceId, @NonNull Block block) {
>             super(TYPE_DELETE, workspaceId, null, block.getId());
> ```

block.getEventWorkspaceId()? or is it the old workspace id at this point?

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java, line 781 at r2](https://reviewable.io:443/reviews/google/blockly-android/568#-KhxgYkXxgVxrfin84HK:-KhxgYkXxgVxrfin84HL:b-ulxke) ([raw file](https://github.com/google/blockly-android/blob/91ef0bb71b8d6e984b38cc992f6a675a7251653b/blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java#L781)):*
> ```Java
>          * @param newValue The value after the event. Booleans are mapped to "true" and "false".
>          */
>         public UIEvent(@BlocklyEvent.UIElement String element, @NonNull Workspace workspace,
> ```

Workspace isn't used.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java, line 104 at r2](https://reviewable.io:443/reviews/google/blockly-android/568#-KhxgpoNjHTu5aikhCEO:-KhxgpoNjHTu5aikhCEP:b-ataa52) ([raw file](https://github.com/google/blockly-android/blob/91ef0bb71b8d6e984b38cc992f6a675a7251653b/blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java#L104)):*
> ```Java
>             block.setEventWorkspaceId(getId());
>             mStats.collectStats(block, true);
>             mController.addPendingEvent(new BlocklyEvent.CreateEvent(block));
> ```

Why did you move the CreateEvent down to Workspace when all the delete events are still up in the Controller? There's also still CreateEvents being fired from BlocklyController.addBlockFromTrashImpl

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/568)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 25 files reviewed at latest revision, 7 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Block.java, line 1207 at r2](https://reviewable.io:443/reviews/google/blockly-android/568#-Khxf_KZk6j_5QBL0iuX:-KhxiUNnsrVQm7aU0euh:bcyt61i) ([raw file](https://github.com/google/blockly-android/blob/91ef0bb71b8d6e984b38cc992f6a675a7251653b/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L1207)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Just a note, if mEventWorkspaceId ever gets modified on a different thread you could have a race condition. It should be fine unless someone is intentionally mucking with threads.
</blockquote></details>

Good point.  Adding a check against this, since our major use cases all would have UI implications.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java, line 488 at r2](https://reviewable.io:443/reviews/google/blockly-android/568#-KhxgKDV4IiXDp5f7KzE:-KhxiaJV0a_renO9iEmH:bhd7puk) ([raw file](https://github.com/google/blockly-android/blob/91ef0bb71b8d6e984b38cc992f6a675a7251653b/blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java#L488)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

block.getEventWorkspaceId()? or is it the old workspace id at this point?
</blockquote></details>

Current implementation has this being the old workspace.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java, line 781 at r2](https://reviewable.io:443/reviews/google/blockly-android/568#-KhxgYkXxgVxrfin84HK:-KhxioqaIiNJuUawAYeN:bt2vr1b) ([raw file](https://github.com/google/blockly-android/blob/91ef0bb71b8d6e984b38cc992f6a675a7251653b/blocklylib-core/src/main/java/com/google/blockly/model/BlocklyEvent.java#L781)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Workspace isn't used.
</blockquote></details>

Fixed.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java, line 104 at r2](https://reviewable.io:443/reviews/google/blockly-android/568#-KhxgpoNjHTu5aikhCEO:-KhxjgIi6ZQi9DE979LU:bawlebz) ([raw file](https://github.com/google/blockly-android/blob/91ef0bb71b8d6e984b38cc992f6a675a7251653b/blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java#L104)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Why did you move the CreateEvent down to Workspace when all the delete events are still up in the Controller? There's also still CreateEvents being fired from BlocklyController.addBlockFromTrashImpl
</blockquote></details>

Given this is a public method (any developer could call it), it seemed more bulletproof to fire the event here.  All necessary references were already available.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/568)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 25 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/568#-:-Khxz62cGTsL5QTcnPyy:bnfp4nl)*

**Pull request merged**
