### PR TITLE
Fix #329 Update FieldNumber to use inf or nan to mean no constraint

### LINKED ISSUE #329: Change FieldNumber to use NaN to mean to restriction
Double.NaN should be used to mean no constraint when passed to setConstraints. We'll also allow Double.POSITIVE_INFINITY for max and Double.NEGATIVE_INFINITY for min to mean no constraint in those two cases.

### PR DESCRIPTION
**Pull request by RoboErikG**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/330)

### CODE REVIEW

**Comment by RoboErikG** [comment]
+@anmatanm +@rachel-fenichel 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/330#-:-KKpK7yync9y-aT5OlEZ:702059670)*

**Comment by AnmAtAnm** [comment]
One update, then :lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java, line 133 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/330#-KKpN_7aYsj7qFXymf6m:-KKpN_7bSUxMe0QiRLjC:-724730185) ([raw file](https://github.com/google/blockly-android/blob/e8151b3441b866543771fdb383e17c679fe1088b/blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java#L133)):*
> ```Java
>         double effectiveMin = Double.isNaN(min) ? -Double.MAX_VALUE : min;
>         double  effectiveMax = Double.isNaN(max) ? Double.MAX_VALUE : max;
>         if (!Double.isNaN(precision)) {
> ```

For readbaility, add final methods hasMinimum(), hasMaximum(), and hasPrecision().

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/330#-:-KKpNo9cmRtsFTf8wZkD:439882029)*

**Comment by RoboErikG** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java, line 133 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/330#-KKpN_7aYsj7qFXymf6m:-KKpP2zsUJyVRaRLP3Z8:1177779850) ([raw file](https://github.com/google/blockly-android/blob/e8151b3441b866543771fdb383e17c679fe1088b/blocklylib-core/src/main/java/com/google/blockly/model/FieldNumber.java#L133)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary>
> For readbaility, add final methods hasMinimum(), hasMaximum(), and hasPrecision().
</details>
Done, though this specific line it's still checking the parameter. Elsewhere in the file I've replaced with hasPrecision.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/330)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/330#-:-KKqffq5MA1nXfIPpPUh:1417088721)*

**Pull request merged**
