### PR TITLE
Refactor NameManager into a map-like class

### PR DESCRIPTION
**Pull request by AnmAtAnm**
Names in blockly refer to things which now have Info objects that store their metadata. Making NameManager a map-like class consolidates the name management with the associated variable or procedure data. This solved a few bugs and cleaned up lots of code.

Next step, solve procedure removal.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/623)

### CODE REVIEW

**Comment by RoboErikG** [comment]
Review status: 0 of 17 files reviewed at latest revision, 11 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java, line 114 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6mcrMiKa1H4n0TgZp:-Kn6mcrMiKa1H4n0TgZq:bgpipxb) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java#L114)):*
> ```Java
>      * @param name The name to add.
>      * @param value The value to associate with the name.
>      * @throws IllegalArgumentException If the name is not valid.
> ```

javadoc @return 

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java, line 136 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6n9VreWnaU0iw91sf:-Kn6n9VreWnaU0iw91sg:b-yz5lit) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java#L136)):*
> ```Java
>      * @param nameRequested The requested name to use.
>      * @param value The value to associate with the name.
>      * @throws IllegalArgumentException If the nameRequested is not valid.
> ```

@return

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java, line 205 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6nPvnu6YEVS4rjpil:-Kn6nPvnu6YEVS4rjpim:b-tuzu9o) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java#L205)):*
> ```Java
>     public String getExisting(String proposedName) {
>         NameEntry<T> existingEntry = mCanonicalMap.get(makeCanonical(proposedName));
>         return existingEntry == null ? proposedName : existingEntry.mDisplayName;
> ```

s/proposedName/null

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 1 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6oqm29lUC4sspuKjH:-Kn6oqm3pxnEu_qNhgHm:b-nhw1dh) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L1)):*
> ```Java
> package com.google.blockly.android.control;
> ```

copyright header

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 12 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6tX9Wqm_48vi8ndcD:-Kn6tX9Wqm_48vi8ndcE:bye15je) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L12)):*
> ```Java
> // This abstract class is required because we really want to store VariableInfoImpl objects
> // inside the WorkspaceStats (with things like field and procedure counts).
> public abstract class VariableNameManager<VI extends VariableInfo> extends NameManager<VI> {
> ```

It looks like the Impl version only depends on getting direct access to the list of procedure names for adding and removing procedures on a VariableInfo. Why not just add the addProcedure and removeProcedure methods to the VariableInfo interface?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 79 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6pYCekROH4tN6FZEi:-Kn6pYCekROH4tN6FZEj:b5fubzl) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L79)):*
> ```Java
>     }
> 
>     public void removeProcedureArg(String varName, String procedureName) {
> ```

javadoc

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java, line 444 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6umH63rJc_iyMjp9u:-Kn6umH63rJc_iyMjp9v:b5t40er) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java#L444)):*
> ```Java
> 
>         @Override
>         protected void markVariableAsProcedureArg(VariableInfoImpl varInfo, String procedureArg) {
> ```

s/procedureArg/procedureName

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java, line 445 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6tzh4IJOWbTikclUp:-Kn6tzh5OwcIWmPnAo54:b-uh9qp8) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java#L445)):*
> ```Java
>         @Override
>         protected void markVariableAsProcedureArg(VariableInfoImpl varInfo, String procedureArg) {
>             if (varInfo.mProcedures == null) {
> ```

Why does the name manager need to know how the variable info adds and removes procedure names?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java, line 452 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6upJrRINtNiEEw6gv:-Kn6upJrRINtNiEEw6gw:b5t40er) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java#L452)):*
> ```Java
> 
>         @Override
>         protected void unmarkVariableAsProcedureArg(VariableInfoImpl varInfo, String procedureArg) {
> ```

s/procedureArg/procedureName

---

*[blocklytest/src/androidTest/java/com/google/blockly/android/control/VariableNameManagerTestImpl.java, line 1 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6v88JTsxkTZ8a2KvR:-Kn6v88JTsxkTZ8a2KvS:baof1b6) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklytest/src/androidTest/java/com/google/blockly/android/control/VariableNameManagerTestImpl.java#L1)):*
> ```Java
> package com.google.blockly.android.control;
> ```

copyright

---

*[blocklytest/src/androidTest/java/com/google/blockly/android/control/VariableNameManagerTestImpl.java, line 26 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6v2Ys32yjGHxOexDi:-Kn6v2Ys32yjGHxOexDj:b-hrnh65) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklytest/src/androidTest/java/com/google/blockly/android/control/VariableNameManagerTestImpl.java#L26)):*
> ```Java
>     @Override
>     protected void unmarkVariableAsProcedureArg(VariableInfoImpl varInfo, String procedureArg) {
>         varInfo.mProcedureNames.add(procedureArg);
> ```

s/add/remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/623)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 19 files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java, line 114 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6mcrMiKa1H4n0TgZp:-KnA06qMlpd1kEv3MUew:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java#L114)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

javadoc @return 
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java, line 136 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6n9VreWnaU0iw91sf:-KnA06Xj1Yu0cqiSTnJH:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java#L136)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

@return
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java, line 205 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6nPvnu6YEVS4rjpil:-KnA0E85Cndqi_kzDPO5:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java#L205)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

s/proposedName/null
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 1 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6oqm29lUC4sspuKjH:-KnA0IOWm6hQzRfuBhrB:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L1)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

copyright header
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 12 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6tX9Wqm_48vi8ndcD:-Kn9hksmT1MpQtQuooVl:b-wswrrf) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L12)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

It looks like the Impl version only depends on getting direct access to the list of procedure names for adding and removing procedures on a VariableInfo. Why not just add the addProcedure and removeProcedure methods to the VariableInfo interface?
</blockquote></details>

And creating new instances, so your suggestion doesn't fully get rid of this class. Still, an improvement.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 79 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6pYCekROH4tN6FZEi:-Kn9mRCB6vFYm9M76Ov3:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L79)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

javadoc
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java, line 444 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6umH63rJc_iyMjp9u:-Kn9mkM9wy5QFFfiDtta:bnpe77y) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java#L444)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

s/procedureArg/procedureName
</blockquote></details>

Removed method, per above.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java, line 445 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6tzh4IJOWbTikclUp:-Kn9mZNrwDyygSxXJq1O:b-emqoa0) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java#L445)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Why does the name manager need to know how the variable info adds and removes procedure names?
</blockquote></details>

Fixed, per above comment.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java, line 452 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6upJrRINtNiEEw6gv:-Kn9miJt0K2G3M-FQeJv:b-sgbdww) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklylib-core/src/main/java/com/google/blockly/android/control/WorkspaceStats.java#L452)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

s/procedureArg/procedureName
</blockquote></details>

Removed method, per suggestion above.

---

*[blocklytest/src/androidTest/java/com/google/blockly/android/control/VariableNameManagerTestImpl.java, line 1 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6v88JTsxkTZ8a2KvR:-Kn9n023MDAbukWEBdXS:b-x3vd36) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklytest/src/androidTest/java/com/google/blockly/android/control/VariableNameManagerTestImpl.java#L1)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

copyright
</blockquote></details>

Done, here and elsewhere.

---

*[blocklytest/src/androidTest/java/com/google/blockly/android/control/VariableNameManagerTestImpl.java, line 26 at r1](https://reviewable.io:443/reviews/google/blockly-android/623#-Kn6v2Ys32yjGHxOexDi:-KnA-IR9FscubJW_q9lk:b58rzly) ([raw file](https://github.com/google/blockly-android/blob/b8f299905459f775c0ae2a3f9fa7931e2cf4cedf/blocklytest/src/androidTest/java/com/google/blockly/android/control/VariableNameManagerTestImpl.java#L26)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

s/add/remove
</blockquote></details>

Removed method

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/623)*

**Comment by RoboErikG** [comment]
Mostly nits. Feel free to submit once fixed. :lgtm_strong: 

---

Review status: 0 of 19 files reviewed at latest revision, 17 unresolved discussions, some commit checks broke.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java, line 137 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAkvxRxuryYaxGmI18:-KnAkvxRxuryYaxGmI19:biaqeqv) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java#L137)):*
> ```Java
>      * @param nameRequested The requested name to use.
>      * @param value The value to associate with the name.
>      * @return The final name used to store V.
> ```

s/V/the value/

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 92 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAlq6A89imE5QJRLDn:-KnAlq6A89imE5QJRLDo:b3tbvh3) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L92)):*
> ```Java
> 
>     /**
>      * Removed any association between the variable {@code argName} with {@code procedureName}. This
> ```

s/Removed/Removes/  s/argName/varName/

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 93 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAlH_MjyfaTlMRYQzS:-KnAlH_MjyfaTlMRYQzT:b-eo46wv) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L93)):*
> ```Java
>     /**
>      * Removed any association between the variable {@code argName} with {@code procedureName}. This
>      * does not remove the variable, if its role as a procedure argument was the last know use.
> ```

nit, empty line between description and params? It looks like we've been really inconsistent in our formatting here. What would you like to be the standard?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 93 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAlzAC8tqcjJsxMKpA:-KnAlzAC8tqcjJsxMKpB:b65jl64) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L93)):*
> ```Java
>     /**
>      * Removed any association between the variable {@code argName} with {@code procedureName}. This
>      * does not remove the variable, if its role as a procedure argument was the last know use.
> ```

nit, no comma after variable.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 94 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAm7Wqoe05us8AGPJ3:-KnAm7Wqoe05us8AGPJ4:bolvy4f) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L94)):*
> ```Java
>      * Removed any association between the variable {@code argName} with {@code procedureName}. This
>      * does not remove the variable, if its role as a procedure argument was the last know use.
>      * @param varName The name of the variable that was once a procedure argument.
> ```

"The name of the variable that was being referenced by the procedure"
"The name of the procedure that is no longer referencing the variable."

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 106 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAoj4vx2NAWgywYzfL:-KnAoj4vx2NAWgywYzfM:b-sfn6n8) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L106)):*
> ```Java
>     /**
>      * Constructs a new VariableInfo object with the given name
>      * @param varName The name fo the variable to create.
> ```

s/fo/of

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/623#-:-KnApGKAfR3AN4mkUy10:b-ay58lz)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 19 files reviewed at latest revision, 17 unresolved discussions, all commit checks successful.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java, line 137 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAkvxRxuryYaxGmI18:-KnBAfHi_nqd6JngnvIf:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/NameManager.java#L137)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

s/V/the value/
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 92 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAlq6A89imE5QJRLDn:-KnAtGyeOfQowpGJhSMw:bt7v9nl) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L92)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

s/Removed/Removes/  s/argName/varName/
</blockquote></details>

Keeping argName, because we are declaring the variable to be an argument with this function.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 93 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAlH_MjyfaTlMRYQzS:-KnAtfCrWsm87Wzzc-7r:bavpvov) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L93)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit, empty line between description and params? It looks like we've been really inconsistent in our formatting here. What would you like to be the standard?
</blockquote></details>

I don't feel a strong need to choose one over the other.  In longer doc comments, the readability improvements  are valuable. In very short comments, I feel the gains are limited. If a function can be clearly described in a sentence, then the spacing increase of another line is proportionally significant (e.g., sentence + blank + param = 150% * (sentence + param)). Neither improve the generated documentation.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 93 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAlzAC8tqcjJsxMKpA:-KnB9kcUJ13uPMW0Kgrz:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L93)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit, no comma after variable.
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 94 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAm7Wqoe05us8AGPJ3:-KnBA5QGgbBk_KFhyQOE:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L94)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

"The name of the variable that was being referenced by the procedure"
"The name of the procedure that is no longer referencing the variable."
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 106 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAoj4vx2NAWgywYzfL:-KnBANt7eg1qRuEJD-Pr:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L106)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

s/fo/of
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/623)*

**Comment by RoboErikG** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java, line 92 at r2](https://reviewable.io:443/reviews/google/blockly-android/623#-KnAlq6A89imE5QJRLDn:-KnBJYltzIqhNsw2IQu5:br32hbn) ([raw file](https://github.com/google/blockly-android/blob/4c2beec776b7e79fa39eb6b3f993e3aa011389f8/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableNameManager.java#L92)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Keeping argName, because we are declaring the variable to be an argument with this function.
</blockquote></details>

I read this as referring to the parameter, which still says varName. Without other context in this file 'argName' doesn't make sense. Did you mean to change the parameter name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/623)*

**Pull request merged**
