### PR TITLE
Merge ProcedureManager mDefinitions and mReferences maps

### PR DESCRIPTION
**Pull request by AnmAtAnm**
This is a WIP on functions.
I replaced the two maps with one, in an effort to reduce the number of parallel keys I need to maintain.
Future step is to do the same with the NameManager, making it a map-like structure to ProcedureBlocks or VariableInfo objects. This also centralizes the canonization of names, and reduces the "surface area" of the name synchronization problem seen during procedure rename.

Also, much more ProcedureManager JavaDocs I missed on the last pass.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/622)

### CODE REVIEW

**Comment by RoboErikG** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-Kmlujux-FN8fq-iWYgn:-Kmlujux-FN8fq-iWYgo:bus1oly) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L88)):*
> ```Java
>     private class ProcedureBlocks {
>         String mName;
>         Block mDefinition;
> ```

Should the definition block also be final?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 181 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmluyJ8GvzdFrrc7Csr:-KmluyJ8GvzdFrrc7Css:b-ic9w5g) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L181)):*
> ```Java
>      *
>      * @param block The block queried.
>      * @return The list of argument for defined or referenced by this block, if it is a procedure
> ```

@return sentence is confusing.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 231 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmlvRgwQmGoBG_BHhCS:-KmlvRgwQmGoBG_BHhCT:b-se5jvo) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L231)):*
> ```Java
>      * Queries whether a procedure block contains a matching registered definition block. Similiar
>      * to {@link #isProcedureDefined(String)}, except it takes in a procedure block. If the block is
>      * a procedure definition, if ensure the block is the same registered definition block.
> ```

s/if/it

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 240 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmlvbjMBddAJrRmeoMl:-KmlvbjMBddAJrRmeoMm:b-izexmz) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L240)):*
> ```Java
>      *         definition or reference mutator.
>      */
>     public boolean containsDefinition(Block procedureBlock) {
> ```

Why isn't this also named isProcedureDefined?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 277 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-Kmlw8q_oAjQZiSl0r21:-Kmlw8q_oAjQZiSl0r22:bz9wqsl) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L277)):*
> ```Java
>      *         definition or reference mutator.
>      */
>     public boolean isReferenceRegistered(Block procedureRefBlock) {
> ```

This seems to only be used for testing. package scope and @VisibleForTesting?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 323 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmlwbKmdNLPQZvNZdig:-KmlwbKmdNLPQZvNZdih:b-1n0k4o) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L323)):*
> ```Java
>         }
>         validateProcedureBlocksMatch(procBlocks.mDefinition, procedureReferenceBlock, false);
>         // TODO: validate definition & reference ProcedureInfo match
> ```

Do you still need this TODO?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/622)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 88 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-Kmlujux-FN8fq-iWYgn:-Kmm3Biy83TZjhFXTp82:btgr91f) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L88)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Should the definition block also be final?
</blockquote></details>

Hmmm... Makes sense. Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 181 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmluyJ8GvzdFrrc7Csr:-Kmm3Zu3iQJXsVkcqU8t:bxk3q0x) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L181)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

@return sentence is confusing.
</blockquote></details>

Rewrote.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 231 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmlvRgwQmGoBG_BHhCS:-Kmm3h4f9ZhO8Q88EJZT:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L231)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

s/if/it
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 240 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmlvbjMBddAJrRmeoMl:-Kmm5p6lJv4i9epkQgew:bszccjr) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L240)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Why isn't this also named isProcedureDefined?
</blockquote></details>

I guess I was thinking this query was asking about this specific block. Did it contain this block? Where the other was asking whether the procedure name was defined by any block. As I describe this, I think I prefer this current name.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 277 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-Kmlw8q_oAjQZiSl0r21:-Kmm6RDUn9K0S3Pl2FDv:b6zrrkh) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L277)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

This seems to only be used for testing. package scope and @VisibleForTesting?
</blockquote></details>

Good catch.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 323 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmlwbKmdNLPQZvNZdig:-Kmm6Vz14XhXjlwMM450:bss4a2b) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L323)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Do you still need this TODO?
</blockquote></details>

Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/622)*

**Comment by RoboErikG** [comment]
Review status: 0 of 11 files reviewed at latest revision, 17 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 277 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-Kmlw8q_oAjQZiSl0r21:-KmmPuPApDudGrs3sG-Q:b-2kuins) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L277)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Good catch.
</blockquote></details>

Did you need the public scope still?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 87 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmSR2jUEzxsXm0v-_G:-KmmSR2jUEzxsXm0v-_H:b-8vhw0r) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L87)):*
> ```Java
>     }
> 
>     private class ProcedureBlocks {
> ```

remove s -> ProcedureBlock

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 417 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmR3rXnM8QrYvUz04q:-KmmR3rXnM8QrYvUz04r:b-kizawi) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L417)):*
> ```Java
>         if (found) {
>             if (referenceBlock.getType().equals(CALL_WITH_RETURN_BLOCK_TYPE)) {
>                 --mCountOfDefinitionsWithReturn;
> ```

You removed the increment from addReference. Need to also remove the decrement from here.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 441 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmRgKiZNeUYXjokhsn:-KmmRgKiZNeUYXjokhso:b5ef21u) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L441)):*
> ```Java
>      */
>     public void addDefinition(Block definitionBlock) {
>         Log.d(TAG, "addDefinition " + getProcedureName(definitionBlock) + " block "
> ```

Nit: remove log

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 445 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmRcZypaDNNwXoSuK9:-KmmRcZypaDNNwXoSuKA:b-lue1fs) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L445)):*
> ```Java
> 
>         if (!isDefinition(definitionBlock)) {
>             throw new IllegalArgumentException("Block is not a procedure definition: " + definitionBlock);
> ```

nit: line length

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 459 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmS0Tio25GSztVBBfN:-KmmS0Tio25GSztVBBfO:b-e8lxqk) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L459)):*
> ```Java
>         }
>         mProcedureNameManager.addName(canonicalProcName);
>         mProcedureBlocks.put(canonicalProcName, new ProcedureBlocks(definitionBlock));
> ```

Should you check if it has a return and increment mCountOfDefinitionsWithReturn?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 526 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmTT7kf7R6oafifVa4:-KmmTT7kf7R6oafifVa5:b-b9kjxx) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L526)):*
> ```Java
>                 mObservers.get(i).onProcedureBlocksRemoved(procBlocks.mName, resultBlocks);
>             }
>         }
> ```

Check if it has a return and decrement mCountOfDefinitionsWithReturn

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 560 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmTj4fXm9oS5LzG9b4:-KmmTj4fXm9oS5LzG9b5:b-44m9mf) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L560)):*
> ```Java
>         final ProcedureInfo oldProcInfo = definitionMutator.getProcedureInfo();
>         String newProcedureNameRequested = updatedProcedureInfo.getProcedureName();
>         Log.d(TAG, "Definition "+Integer.toHexString(definition.hashCode())+"\n\tnewProcedureNameRequested = " + newProcedureNameRequested);
> ```

Nit: Logs

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 564 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmU4q6ZaVLERM0fDPc:-KmmU4q6ZaVLERM0fDPd:b-euv2p9) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L564)):*
> ```Java
>         Log.d(TAG, "\tisFuncRename = " + isFuncRename);
>         final String newProcedureName = !isFuncRename ? originalProcedureName
>                 : mProcedureNameManager.generateUniqueName(newProcedureNameRequested, true);
> ```

Does this allow changing the case? eg procedurename -> procedureName

---

*[blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldInputView.java, line 48 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmUhZ0okjqS3JeJ14h:-KmmUhZ0okjqS3JeJ14i:b2ni78f) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldInputView.java#L48)):*
> ```Java
>         public void afterTextChanged(Editable s) {
>             if (mInputField != null) {
>                 if (mInputField.getBlock() != null) { Log.d(TAG, "Block "+Integer.toHexString(mInputField.getBlock().hashCode()) + ": New input view text: " + s); }
> ```

log

---

*[blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureDefinitionMutator.java, line 148 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmV4-EvOgyG661DFHr:-KmmV4-EvOgyG661DFHs:bb7k6d0) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureDefinitionMutator.java#L148)):*
> ```Java
>         ProcedureInfo xmlInfo = ProcedureInfo.parseImpl(parser);
>         FieldInput nameField = getNameField();
>         Log.d("ProcedureDef", "parseAndValidateMutationXml for block " + Integer.toHexString(mBlock.hashCode()) + ":"
> ```

logs

---

*[blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureDefinitionMutator.java, line 293 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmVH4S44AY5PmCsrDW:-KmmVH4S44AY5PmCsrDX:bb7k6d0) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureDefinitionMutator.java#L293)):*
> ```Java
>                 Log.d("ProcedureDef", "Block " + Integer.toHexString(mBlock.hashCode())
>                         + ": updateBlock(): field name: " + nameField.getText()
>                         + ", new name: " + mProcedureInfo.getProcedureName()
> ```

logs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/622)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 11 files reviewed at latest revision, 17 unresolved discussions, some commit checks broke.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 277 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-Kmlw8q_oAjQZiSl0r21:-KmmvEK1YgC3cqsog_HE:bt2vr1b) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L277)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Did you need the public scope still?
</blockquote></details>

Fixed.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 87 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmSR2jUEzxsXm0v-_G:-Kmmuxn253MWNYmVmaEB:bn73i4s) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L87)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

remove s -> ProcedureBlock
</blockquote></details>

Intentionally plural.  It is a set of blocks, including definition block and possibly multiple reference blocks.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 417 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmR3rXnM8QrYvUz04q:-KmmvglxYo-9JRGjT76B:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L417)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

You removed the increment from addReference. Need to also remove the decrement from here.
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 441 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmRgKiZNeUYXjokhsn:-KmmrEqyucB3suA3NND-:b-di52w0) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L441)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Nit: remove log
</blockquote></details>

Because I'm still debugging this issues and this isn't going into `develop` branch, I'm going to leave these for now.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 445 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmRcZypaDNNwXoSuK9:-KmmoeEK6tMnL88TEh19:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L445)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

nit: line length
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 459 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmS0Tio25GSztVBBfN:-KmmrAqfBp7exGnVHr-U:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L459)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Should you check if it has a return and increment mCountOfDefinitionsWithReturn?
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 526 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmTT7kf7R6oafifVa4:-KmmrG9aPliG82HIhaJV:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L526)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Check if it has a return and decrement mCountOfDefinitionsWithReturn
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 560 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmTj4fXm9oS5LzG9b4:-KmmrYCOGxie0Onpw8UI:b-4onwu4) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L560)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Nit: Logs
</blockquote></details>

Will remove before I merge into develop.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java, line 564 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmU4q6ZaVLERM0fDPc:-Kmmri9m_sTncK7aiPMK:b2mq80m) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/android/control/ProcedureManager.java#L564)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Does this allow changing the case? eg procedurename -> procedureName
</blockquote></details>

Good point.  Fixed, and  I've added this to my use cases to test.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldInputView.java, line 48 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmUhZ0okjqS3JeJ14h:-KmmviHQGUxOj_G6kCYA:b-jkrw6g) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/android/ui/fieldview/BasicFieldInputView.java#L48)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

log
</blockquote></details>

Will remove before merging into develop.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureDefinitionMutator.java, line 148 at r1](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmV4-EvOgyG661DFHr:-KmmvuAhPBgsE1W-lcKA:b-jkrw6g) ([raw file](https://github.com/google/blockly-android/blob/4fe4be8a50ef4596a9461e4e1e5846a590013fa2/blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureDefinitionMutator.java#L148)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

logs
</blockquote></details>

Will remove before merging into develop.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureDefinitionMutator.java, line 293 at r2](https://reviewable.io:443/reviews/google/blockly-android/622#-KmmVH4S44AY5PmCsrDW:-KmmvoNP9gXLYEaahFkk:b-jkrw6g) ([raw file](https://github.com/google/blockly-android/blob/a23b12e1b607c256585c0b2a2dc26253882887cb/blocklylib-core/src/main/java/com/google/blockly/model/mutator/ProcedureDefinitionMutator.java#L293)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

logs
</blockquote></details>

Will remove before merging into develop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/622)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 17 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/622#-:-Kmn7863kn7APeLEaXs1:bnfp4nl)*

**Pull request merged**
