### PR TITLE
Adding BlockExtensions and Mutators

### PR DESCRIPTION
**Pull request by AnmAtAnm**
Adds the base classes of BlockExtensions and Mutators, as well as the core infrastructure to support them in both JSON block definitions and XML serialization.  Does not add UI support for editable mutators.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/545)

### CODE REVIEW

**Comment by RoboErikG** [comment]
Review status: 0 of 12 files reviewed at latest revision, 8 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java, line 401 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFCOf14TbNpR5JVfOu:-KeFCOf2WuYAS8Ac88Wj:brrom7q) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java#L401)):*
> ```Java
>      */
>     @Nullable
>     protected Map<String, BlockExtension> getBlockExtensions() {
> ```

Outside the scope of this CL, but I wonder if it would be better if all these get methods which return something to pass to the BlockFactory were of the form updateX(BlockFactory) so they could apply updates to the factory directly.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java, line 271 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFEwlhhqTIHqYkYg_v:-KeFEwlhhqTIHqYkYg_w:b-w409lj) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java#L271)):*
> ```Java
> 
>     /**
>      * @return The name of the {@link Mutator} add to all instances of this BlockDefinition, if any.
> ```

This comment is confusing. I think you mashed two sentences together?

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java, line 280 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFFKwod9ibDfCeC14c:-KeFFKwod9ibDfCeC14d:b-jeiwe6) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java#L280)):*
> ```Java
> 
>     /**
>      * @return A list of extensions names to apply to all instances of this BlockDefinition.
> ```

remove the s on extensions

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java, line 349 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFFVlIkmMLnKphLpgY:-KeFFVlIkmMLnKphLpgZ:b3f3e7p) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java#L349)):*
> ```Java
>      * @return A list of extension names if provided. Otherwise, null.
>      * @throws BlockLoadingException If "extensions" attribute is not an array.
>      * @throws JSONException If JSON is array does not contain strings.
> ```

throws is a bit confusing maybe, "If the extensions key does not contain a string or an array of strings."

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 527 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFLDEuk38g8CqeVXz3:-KeFLDEvQERNs1GGkaQN:bhc6cui) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L527)):*
> ```Java
>                             }
>                         } else if (tagname.equalsIgnoreCase("mutation")) {
>                             String elementStr = BlocklyXmlHelper.captureElement(parser);
> ```

It seems a little odd to parse into a string and then wrap it back into an XMLParser when you apply it to the Block. Is there a simple way to leave it as XML or was the String needed to make it reusable?

---

*[blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java, line 382 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFJqMupYxUueFkm_ss:-KeFJqMvOvmSaeWxUVQl:bnditju) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java#L382)):*
> ```Java
>         int event = parser.getEventType();
>         if (event != XmlPullParser.START_TAG) {
>             throw new XmlPullParserException("Expected cal to begin at START_TAG");
> ```

missing l -> call

---

*[blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java, line 384 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFJx-KxX1L_jXdJl4p:-KeFJx-KxX1L_jXdJl4q:bkkwaxu) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java#L384)):*
> ```Java
>             throw new XmlPullParserException("Expected cal to begin at START_TAG");
>         }
>         int depth = -1;  // Will be increment below, at START_TAG:
> ```

missing 'ed' -> incremented. Why -1, though? Below you're checking for < 0. Can't you check for == 0?

---

*[blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java, line 441 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFLexMpktaNoyDIscL:-KeFLexN61n4iCnGbJuC:b7r5xui) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java#L441)):*
> ```Java
>     }
> 
>     public static void updateMutator(
> ```

Comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/545)*

**Comment by vicng** [comment]
Review status: 0 of 12 files reviewed at latest revision, 17 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Block.java, line 106 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFMeVgLmLaDXT-_mLv:-KeFMeVgLmLaDXT-_mLw:byheh1z) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L106)):*
> ```Java
>         String mutatorName = definition.getMutatorName();
>         if (mutatorName != null) {
>             factory.applyExtension(mutatorName, this, true);
> ```

We should separate mutators and extensions explicitly in the BlockFactory (I was planning on making this change in iOS soon). I think it's confusing applying a mutator through an extension -- why even define a mutator field if this is the case?

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockExtension.java, line 46 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFUWT-FDaKb4F2w-7t:-KeFUWT0h1Ut2wZT8snP:b-80z19o) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockExtension.java#L46)):*
> ```Java
>  */
> public interface BlockExtension {
>     Map<String, BlockExtension> STANDARD_EXTENSIONS = Collections.EMPTY_MAP;  // TODO
> ```

TODO?

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 206 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVXrZxrCrELMffXtr:-KeFVXrZxrCrELMffXts:b-rbedap) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L206)):*
> ```Java
>             } else {
>                 // Make this explicit
>                 throw new IllegalStateException(
> ```

Can't this be checked by looping through blocks?

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 224 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVOdZTylZJHPAHhEQ:-KeFVOdZTylZJHPAHhER:brhumzt) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L224)):*
> ```Java
>         boolean result = (mDefinitions.remove(definitionName) != null);
>         if (result && !mBlockRefs.isEmpty()) {
>             Log.w(TAG, "Removing BlockDefinition \"" + definitionName + "\" while blocks active.");
> ```

Same here.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 240 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVWRWeMcSM-WaARh3:-KeFVWRWeMcSM-WaARh4:b-1kzc9c) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L240)):*
> ```Java
>         boolean result = (mExtensions.remove(extensionName) != null);
>         if (result && !mBlockRefs.isEmpty()) {
>             Log.w(TAG, "Removing BlockExtension \"" + extensionName + "\" while blocks active.");
> ```

And here.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 414 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVc_NhnzC0ayaurXA:-KeFVc_NhnzC0ayaurXB:bwrm4p9) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L414)):*
> ```Java
>      * @param block The block to apply it to.
>      */
>     public void applyExtension(String extensionName, Block block, boolean isMutator)
> ```

As noted before, I think it's confusing to apply a mutator through an extension.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 630 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVt19dWKQisWDaSnt:-KeFVt19dWKQisWDaSnu:b-hxgnnf) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L630)):*
> ```Java
>      */
>     public void clear() {
>         mBlockRefs.clear();  // What if these blocks exist on the workspace?
> ```

Is this a note to fix later?

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFLAeX15stpYDbs8hh:-KeFLAeY7CyGVgrJnw9Z:b6okr9r) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java#L33)):*
> ```Java
>  * extensions and mutators</a>.
>  */
> public abstract class Mutator {
> ```

Why not an interface?

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java, line 59 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFXu7uq9izS-XbTc1H:-KeFXu7uq9izS-XbTc1I:b-qgqsqn) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java#L59)):*
> ```Java
>     public abstract void update(Block block, XmlPullParser parser)
>             throws IOException, XmlPullParserException;
> }
> ```

I really think it's better to have an explicit mutateBlock() method, rather than relying on update() to do it. The problem is that update(...) forces any actual mutations to do be done via an XML update. Outside users would then need to know about the internal XML representation of a mutator to perform a mutation, which is error-prone.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/545)*

**Comment by RoboErikG** [comment]
Review status: 0 of 12 files reviewed at latest revision, 17 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Block.java, line 106 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFMeVgLmLaDXT-_mLv:-KeFl_fD_lZqx8vfe5NI:b-sgqwww) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L106)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

We should separate mutators and extensions explicitly in the BlockFactory (I was planning on making this change in iOS soon). I think it's confusing applying a mutator through an extension -- why even define a mutator field if this is the case?
</blockquote></details>

This is also how it's implemented on web. It would make sense to add an explicit registerMutator(String, Mutator) method on BlockFactory that wraps it in an extension for you the way web does.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 206 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVXrZxrCrELMffXtr:-KeFm98uS7Ql_c7I8e6A:bnmu9ya) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L206)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Can't this be checked by looping through blocks?
</blockquote></details>

It's not really worth the effort. If they're modifying the list of extensions after blocks were created they're in uncharted waters already.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java, line 59 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFXu7uq9izS-XbTc1H:-KeFmbMeXBKk8vMVcG6h:b78bomm) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java#L59)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

I really think it's better to have an explicit mutateBlock() method, rather than relying on update() to do it. The problem is that update(...) forces any actual mutations to do be done via an XML update. Outside users would then need to know about the internal XML representation of a mutator to perform a mutation, which is error-prone.
</blockquote></details>

This is the API Blockly's default UI will use. Developers are free to add a mutateBlock() method and call it from their UI, but this is strictly required to support mutations from XML.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/545)*

**Comment by vicng** [comment]
Review status: 0 of 12 files reviewed at latest revision, 17 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java, line 59 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFXu7uq9izS-XbTc1H:-KeGBwBU1DoZIkY_qyBy:brzkqal) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java#L59)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

This is the API Blockly's default UI will use. Developers are free to add a mutateBlock() method and call it from their UI, but this is strictly required to support mutations from XML.
</blockquote></details>

I'm not saying `update()` shouldn't exist. I'm saying it shouldn't do two things: update state from XML and apply the mutation. Any default behavior in the library can call `update()` then `mutateBlock()` on a mutator.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/545)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 12 files reviewed at latest revision, 17 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java, line 401 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFCOf14TbNpR5JVfOu:-KeFpfaw3v2RiPqQsqhz:b-lbz90s) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java#L401)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Outside the scope of this CL, but I wonder if it would be better if all these get methods which return something to pass to the BlockFactory were of the form updateX(BlockFactory) so they could apply updates to the factory directly.
</blockquote></details>

Granted, the creation of a new map is  not ideal, I think this form is more standard for Java conventions, and is a more resilent API... slightly. If the BlockFactory methods change (hopefully rarely), it doesn't affect the AbstractBlocklyActivity or BlocklyActivityHelper.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Block.java, line 106 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFMeVgLmLaDXT-_mLv:-KeFqQJIXgrXj1gKHbp7:b-pbiepx) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L106)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

This is also how it's implemented on web. It would make sense to add an explicit registerMutator(String, Mutator) method on BlockFactory that wraps it in an extension for you the way web does.
</blockquote></details>

I started with `MutatorFactory.createMutator(Block)`, but it looked suspiciously similar to `BlockExtension`, with its singular `.applyTo(Block)`, in structure.

Further, adding the mutator may require more initialization than just the mutator assignment. I believe the `BlockExtension.applyTo()` is more in line. It isn't clear to me that `.createMutator(..)` would be the place to do such initialization.

It does separate the namespace between the two. But that is about the only benefit I see with these suggestions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java, line 271 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFEwlhhqTIHqYkYg_v:-KeFt47zKx_mo-r7KXSC:ba8x5ql) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java#L271)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

This comment is confusing. I think you mashed two sentences together?
</blockquote></details>

Rewrote

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java, line 280 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFFKwod9ibDfCeC14c:-KeFt8RJ4vOrPqhD6whs:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java#L280)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

remove the s on extensions
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java, line 349 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFFVlIkmMLnKphLpgY:-KeFtXvrtxfuNKLFHzr-:byd5f42) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockDefinition.java#L349)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

throws is a bit confusing maybe, "If the extensions key does not contain a string or an array of strings."
</blockquote></details>

Rewrote.

I'm intentionally not mentioning that this will recover from a string without an array.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockExtension.java, line 46 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFUWT-FDaKb4F2w-7t:-KeFthgqJxU6emtgBxqZ:bv86i3q) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockExtension.java#L46)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

TODO?
</blockquote></details>

I have no standard extension implementations yet.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 206 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVXrZxrCrELMffXtr:-KeFtwsELgnglXMcOJTl:b-vqyj1c) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L206)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

It's not really worth the effort. If they're modifying the list of extensions after blocks were created they're in uncharted waters already.
</blockquote></details>

The blocks do not (currently) maintain a reference to the extensions that have been applied to them, so there is no references to check.  If someone wants to do this, they can patch the code and allow this, and then support is out of our hands. I'd be happy to discuss developer's use cases, if they need this.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 414 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVc_NhnzC0ayaurXA:-KeFuXnPeDwYfIW8UW3n:b-24l6qw) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L414)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

As noted before, I think it's confusing to apply a mutator through an extension.
</blockquote></details>

Mirroring the JavaScript API makes porting easier, IMO.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 527 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFLDEuk38g8CqeVXz3:-KeFueFFLmbGIk6rCOpV:bxpc0y5) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L527)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

It seems a little odd to parse into a string and then wrap it back into an XMLParser when you apply it to the Block. Is there a simple way to leave it as XML or was the String needed to make it reusable?
</blockquote></details>

I can't both pause the pull parser and continue parsing to the end of the XML element.

Also, this gives some assurance that the mutation String is a single well formed element, and deserializing will not affect the remaining usage of the pull parser.

Finally, it means the serialize and update methods are symmetric with respect to the XmlSerializer and XmlPullParser both starting before the `<mutation>` start tag.

The possibly better alternative would be to parse it into a bunch of [DOM objects](https://developer.android.com/reference/org/w3c/dom/package-summary.html), but that is unusual for Android.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 630 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVt19dWKQisWDaSnt:-KeFv5oy0axOKiKe7_hq:b-d2jgly) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L630)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Is this a note to fix later?
</blockquote></details>

It's an open question, beyond the scope of this PR.  I'm not sure what we should be doing here.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java, line 33 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFLAeX15stpYDbs8hh:-KeFvFTDT7nRY9J8WBlv:b-ltvsvk) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java#L33)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Why not an interface?
</blockquote></details>

Because `compose()` and `decompose()` are optional (though not yet present). It seemed silly to require mutators without UI's to implement no-op methods.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java, line 59 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFXu7uq9izS-XbTc1H:-KeFvp-yJYwQG4SyF_NU:b2qeanv) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java#L59)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

This is the API Blockly's default UI will use. Developers are free to add a mutateBlock() method and call it from their UI, but this is strictly required to support mutations from XML.
</blockquote></details>

What 'outside users' use case are you considering?

I think this is sufficient. Consider a Blockly change event describing a mutation. I can still call `block.getMutator()`, cast it to the expected `Mutator` type, and get the inner state without understanding the XML.

---

*[blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java, line 384 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFJx-KxX1L_jXdJl4p:-KeFxLFI_0qVzXM66c44:bhrp03r) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java#L384)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

missing 'ed' -> incremented. Why -1, though? Below you're checking for < 0. Can't you check for == 0?
</blockquote></details>

Sure. I can do that.
It just made sense for me to have the root block be 0, instead of depth 1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/545)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 12 files reviewed at latest revision, 17 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 224 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVOdZTylZJHPAHhEQ:-KeGHbMyLx-lvi-D6vAG:b-q64pkt) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L224)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

See above.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java, line 240 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFVWRWeMcSM-WaARh3:-KeGHd1zCJUNTf2XAwMP:b-q64pkt) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/BlockFactory.java#L240)):*
<details><summary><i>Previously, vicng wrote…</i></summary><blockquote>

And here.
</blockquote></details>

See above.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java, line 59 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFXu7uq9izS-XbTc1H:-KeGHQMRqbSmjL4zTJVH:b-kh9vjz) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java#L59)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

What 'outside users' use case are you considering?

I think this is sufficient. Consider a Blockly change event describing a mutation. I can still call `block.getMutator()`, cast it to the expected `Mutator` type, and get the inner state without understanding the XML.
</blockquote></details>

What is the use case for having a Mutator with state that isn't reflected in the block?

---

*[blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java, line 382 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFJqMupYxUueFkm_ss:-KeGHZKBvBW6QNFvdeOD:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java#L382)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

missing l -> call
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java, line 441 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFLexMpktaNoyDIscL:-KeGH_DhjyZZbAwK8Fub:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/utils/BlocklyXmlHelper.java#L441)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/545)*

**Comment by RoboErikG** [comment]
Review status: 0 of 12 files reviewed at latest revision, 17 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java, line 59 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFXu7uq9izS-XbTc1H:-KeGFMqY6WqMN570fneh:b-vajg0j) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Mutator.java#L59)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

What 'outside users' use case are you considering?

I think this is sufficient. Consider a Blockly change event describing a mutation. I can still call `block.getMutator()`, cast it to the expected `Mutator` type, and get the inner state without understanding the XML.
</blockquote></details>

I don't think there's a strong case to add a mutateBlock method to the API. This is equivalent behavior to web's domToMutation, and if the Blockly library on Android only performs mutations from xml then it doesn't make sense to add more to the public API.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/545)*

**Comment by RoboErikG** [comment]
Review status: 0 of 12 files reviewed at latest revision, 17 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Block.java, line 106 at r1](https://reviewable.io:443/reviews/google/blockly-android/545#-KeFMeVgLmLaDXT-_mLv:-KeGNBd3ao8DzTsQX30O:btgu3an) ([raw file](https://github.com/google/blockly-android/blob/dc2e201e9fcaef06c9a9ead4c602e425a8d2af3c/blocklylib-core/src/main/java/com/google/blockly/model/Block.java#L106)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I started with `MutatorFactory.createMutator(Block)`, but it looked suspiciously similar to `BlockExtension`, with its singular `.applyTo(Block)`, in structure.

Further, adding the mutator may require more initialization than just the mutator assignment. I believe the `BlockExtension.applyTo()` is more in line. It isn't clear to me that `.createMutator(..)` would be the place to do such initialization.

It does separate the namespace between the two. But that is about the only benefit I see with these suggestions.
</blockquote></details>

Take a look at the way Rachel implemented it on web. It shares the same namespace and it's applied to blocks as an extension, but provides a more structured API for registering mutators and does some validation.

As a separate discussion, we should consider adding an onAttach/onDestroy API similar to Mutators on iOS to allow for extra initialization.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/545)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/545#-:-KeLciiMc9EQ238cx8ZF:bnfp4nl)*

**Pull request merged**
