### PR TITLE
WIP on allowing variables to be deleted/renamed

### PR DESCRIPTION
**Pull request by RoboErikG**
Progress on Issue #22 ready for early review.

TODO:
- Tests
- Cleanup pass on new code and comments

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/343)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 117 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMaejOGUgClw30ChQW:-KOM_iWFKAskC39VZyy9:-198551460) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L117)):*
> ```Java
>     private VariableCallback mVariableCallback = null;
> 
>     private VariableCallback mVariableViewCallback = new VariableCallback() {
> ```

mVariableViewCallback is descriptive to me, when compared to mVariableCallback.  Can you add a comment on how these differ, and possibly rename one?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 544 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMdTBlOpKRLQtk6vJ8:-KOMdTBlOpKRLQtk6vJ9:1640822470) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L544)):*
> ```Java
> 
>     /**
>      * Takes a block and adds it to the root blocks, disconnecting previous or output connections
> ```

Per discussion, remove.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 626 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMaw3jYHmHqh2hLa5r:-KOMaw3jYHmHqh2hLa5s:1400414456) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L626)):*
> ```Java
>      * @return The list of blocks using that variable.
>      */
>     public List<Block> getVariableBlocks(String variable) {
> ```

Does ordering matter? Should this be a Set?

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 636 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMda2auIRo0956MaUw:-KOMda2bchD3qS8UxyVM:723617357) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L636)):*
> ```Java
>      *
>      * @param variable The variable to remove.
>      * @param forced True to skip the variable callback check and remove the variable and all blocks
> ```

Line length

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 1220 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMeNtFzlcWDa1JTPeU:-KOMeNtGem0J_Vpxb04V:1185562836) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L1220)):*
> ```Java
>      *                    the previous block if allowed.
>      */
>     private void extractBlockAsRootImpl(Block block, boolean includeNext) {
> ```

"includeNext" means next is "extracted", also.  Sounds counter-intuitive.  Maybe "reattachNext", or mor accurately, "maybeReattachNext"? The meaning of the boolean flips, but then positive / true means additional action.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java, line 249 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMbU9WXg1LalTbvbUR:-KOMbU9WXg1LalTbvbUS:1426170733) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java#L249)):*
> ```Java
>      * @return A list of all blocks referencing the given variable.
>      */
>     public List<Block> getVariableBlocks(String variable) {
> ```

Does ordering matter? Should this be a Set?

Whichever collection, should it be passed in to minimize allocations if called multiple times, since this is exposed publicly on the controller.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/343)*

**Comment by RoboErikG** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 117 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMaejOGUgClw30ChQW:-KOMhkFBKTGsypOfSEa9:-564894713) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L117)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary>
> mVariableViewCallback is descriptive to me, when compared to mVariableCallback.  Can you add a comment on how these differ, and possibly rename one?
</details>
Woops, that should have been deleted. I made these separate classes to remove exactly this confusion.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 544 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMdTBlOpKRLQtk6vJ8:-KOMhwq_-j1ithNYXj9F:-499146009) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L544)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary>
> Per discussion, remove.
</details>
Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 626 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMaw3jYHmHqh2hLa5r:-KOMkr7gh_NmOMGlaMxF:-225287110) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L626)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary>
> Does ordering matter? Should this be a Set?
</details>
Ordering only matters for testing, where having a different order could cause a different event stream (with the same end model state). For example [Set <var1> to [get <var1>]] could send one or two delete events if var1 is deleted depending on which block gets deleted first.

On the performance side, this is trading off more time spent checking if we've already added a block vs object allocation to iterate through the list of blocks elsewhere.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 636 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMda2auIRo0956MaUw:-KOMlmvNyVFaehSaSmjj:1084675344) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L636)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary>
> Line length
</details>
Are you sure? It looks like it's exactly 100 chars to me.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 1220 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMeNtFzlcWDa1JTPeU:-KOMn5FeFKc--kXxdynf:-499146009) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L1220)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary>
> "includeNext" means next is "extracted", also.  Sounds counter-intuitive.  Maybe "reattachNext", or mor accurately, "maybeReattachNext"? The meaning of the boolean flips, but then positive / true means additional action.
</details>
Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java, line 249 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMbU9WXg1LalTbvbUR:-KOfGZUoI8KdDoxB6cyl:1551590694) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java#L249)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary>
> Does ordering matter? Should this be a Set?
> 
> Whichever collection, should it be passed in to minimize allocations if called multiple times, since this is exposed publicly on the controller.
</details>
Same answer re: ordering as above. I added an optional parameter for passing a list to use in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/343)*

**Comment by RoboErikG** [comment]
+@anmatanm +@rachel-fenichel 

---

Review status: 15 of 23 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/343#-:-KOkUkn1TxwWsL58g6ps:702059670)*

**Comment by AnmAtAnm** [comment]
*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 580 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOkZyeLSelyDM9iYMA9:-KOkZyeMYegf5W0hmf0c:blhfe5i) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L580)):*
> ```Java
>      * @return The actual variable name that was created or null if creation was blocked.
>      */
>     public String addVariable(String variable, boolean forced) {
> ```

Looking at this in use in the demo activities, I think this is better split into two methods:
addVariable ("name") // The forced variety
promptAddVariable("name") // The unforced variety.  Or alternatively, maybeAddVariable(..)

The boolean value is probably rarely false in the app code, and the boolean isn't informative if, as a reader, you weren't expecting it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/343)*

**Comment by AnmAtAnm** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 636 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMda2auIRo0956MaUw:-KOkaL2XvLiNa8N34eMg:bq0gi2w) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L636)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary>
> Are you sure? It looks like it's exactly 100 chars to me.
</details>
The 's' wraps in reviewable, even when the page view is zoomed out (large horizontal margins).  The "e." in "workspaces." does the same, below. Maybe reviewable is wrong.

---

*[blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java, line 1046 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOkcefVW8A2QUS4cmW8:-KOkcefWhOWNe7Dex_fT:bf1qr98) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java#L1046)):*
> ```Java
>     }
> 
>     public void testVariableCallbacks() {
> ```

Prefer using separate test methods for each case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/343)*

**Comment by rachel-fenichel** [comment]
Reviewed 1 of 17 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java, line 859 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOlhrirANCXySkiZWRW:-KOlhrisqHoNrSE649lm:bbusigz) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java#L859)):*
> ```Java
>             }
> 
>             mDeleteDialog.setConroller(controller);
> ```

Controller is misspelllled

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 603 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOliu7adli7ca2CCaMv:-KOliu7adli7ca2CCaMw:b-m82px7) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L603)):*
> ```Java
>      * @return The list of blocks using that variable.
>      */
>     public List<Block> getVariableBlocks(String variable) {
> ```

Maybe getBlocksWithVariable(String variable)

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 717 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOljl1E5ofhnvFyp5YP:-KOljl1FhHWfSMY0L0-9:b-ulx4nn) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L717)):*
> ```Java
>      * @return True if the block was removed, false if it wasn't found.
>      */
>     public boolean removeBlockAndInputBlocks(Block block) {
> ```

Why use "remove" instead of "delete"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/343)*

**Comment by AnmAtAnm** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 636 \[r1\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOMda2auIRo0956MaUw:-KOlk6DzRqgFr3qVkiRc:b-3s8qb8) ([raw file](https://github.com/google/blockly-android/blob/a80358d17bbbd1f4724d115cfc04bbc258b7e2dd/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L636)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary>
> The 's' wraps in reviewable, even when the page view is zoomed out (large horizontal margins).  The "e." in "workspaces." does the same, below. Maybe reviewable is wrong.
</details>
(Per offline discussion, ignore.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/343)*

**Comment by RoboErikG** [comment]
Review status: 12 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java, line 859 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOlhrirANCXySkiZWRW:-KOll9riY3q7zf0ItB_f:-499146009) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklylib-core/src/main/java/com/google/blockly/android/AbstractBlocklyActivity.java#L859)):*
<details><summary><i>Previously, rachel-fenichel wrote…</i></summary>
> Controller is misspelllled
</details>
Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 580 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOkZyeLSelyDM9iYMA9:-KOllByWCrwc1PtBI7Ss:-499146009) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L580)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary>
> Looking at this in use in the demo activities, I think this is better split into two methods:
> addVariable ("name") // The forced variety
> promptAddVariable("name") // The unforced variety.  Or alternatively, maybeAddVariable(..)
> 
> The boolean value is probably rarely false in the app code, and the boolean isn't informative if, as a reader, you weren't expecting it.
</details>
Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 603 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOliu7adli7ca2CCaMv:-KOllP3zqkKD4I83LW-5:-499146009) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L603)):*
<details><summary><i>Previously, rachel-fenichel wrote…</i></summary>
> Maybe getBlocksWithVariable(String variable)
</details>
Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 717 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOljl1E5ofhnvFyp5YP:-KOllaaBEzakeAuKdDkB:1897591863) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L717)):*
<details><summary><i>Previously, rachel-fenichel wrote…</i></summary>
> Why use "remove" instead of "delete"?
</details>
Everything else uses remove, except for my callback method which I just renamed to onRemoveVariable.

---

*[blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java, line 1046 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOkcefVW8A2QUS4cmW8:-KOlnXz79WSSf4KQBsXQ:-499146009) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklytest/src/androidTest/java/com/google/blockly/android/control/BlocklyControllerTest.java#L1046)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary>
> Prefer using separate test methods for each case.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/343)*

**Comment by AnmAtAnm** [comment]
:lgtm:

---

Reviewed 8 of 12 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/343#-:-KOlwI-VQw80zd0n4_wh:bnfp4nl)*

**Comment by rachel-fenichel** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 717 \[r2\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOljl1E5ofhnvFyp5YP:-KOlwsZnefokxgj4iSm7:bgy7etn) ([raw file](https://github.com/google/blockly-android/blob/7d8ff7ef9ab3ceb356857af18bf4a566de7651ae/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L717)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary>
> Everything else uses remove, except for my callback method which I just renamed to onRemoveVariable.
</details>
Right, but we generally speak of variable deletion instead of removal.  I think the message mentions deletion, and the web implementation calls it deletion.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java, line 649 \[r3\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOlwhG71iaLqnnWp5eJ:-KOlwhG71iaLqnnWp5eK:barn19u) ([raw file](https://github.com/google/blockly-android/blob/252242cf639589c9e6010f0bc472772de89f433f/blocklylib-core/src/main/java/com/google/blockly/android/control/BlocklyController.java#L649)):*
> ```Java
> 
>     /**
>      * Renames a variable in the workspace. If a variable already exists with the new name it will
> ```

What does "it" refer to here (which one will be updated to be unique)?

---

*[blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java, line 257 \[r3\]](https://reviewable.io:443/reviews/google/blockly-android/343#-KOlxc0kkkc_PTbdCzrE:-KOlxc0kkkc_PTbdCzrF:bebs0go) ([raw file](https://github.com/google/blockly-android/blob/252242cf639589c9e6010f0bc472772de89f433f/blocklylib-core/src/main/java/com/google/blockly/model/Workspace.java#L257)):*
> ```Java
>      *
>      * @param variable The variable to get blocks for.
>      * @param resultList An optional list to put the results in. This object will be returned if not
> ```

This API is baffling to me.  Why pass in the list and then return it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/343)*

**Pull request merged**
