### PR TITLE
2016_05-16 drawables

### PR DESCRIPTION
**Pull request by AnmAtAnm**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/323)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
PTAL @roboerikg 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/323#-:-KKG6ks71B-LYFytSDGK:1290518790)*

**Comment by RoboErikG** [comment]
Code :lgtm: We still need hat assets that aren't lopsided. ;)

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/323#-:-KKL8Eoz6uXZQE458TUy:1235906194)*

**Comment by rachel-fenichel** [comment]
http://files.brightside.me/files/news/part_11/112505/355955-650-1457532998-572b7abb79246ed26bf4ff42b53d2e93.jpg

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/323#-:-KKLAbP66P6wEwovLvTX:-2146562568)*

**Comment by AnmAtAnm** [comment]
PTAL @roboerikg 
Fixed the top_start_hat blocks and added code to support them in the vertical stacking BlockView style.

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/323#-:-KL435JA9yL0EoPovHHg:-2016975704)*

**Comment by AnmAtAnm** [comment]
Fixed the RTL files.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/323#-:-KLI0vNseWcv3Ny4ldI-:-1122226931)*

**Pull request merged**
