### PR TITLE
Support custom categories and add VariablesCategory

### PR DESCRIPTION
**Pull request by RoboErikG**
This adds support for labels and buttons to the flyouts and sets up a
way to create custom categories. It also adds a custom category for
variables that dynamically builds the blocks for the variables
category.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/523)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
Reviewed 16 of 19 files at r2.
Review status: 16 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/FlyoutController.java, line 63 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy1P2GCl0RCbyuxivf:-Kcy1P2GCl0RCbyuxivg:b-oizhlc) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/android/control/FlyoutController.java#L63)):*
> ```Java
>         @Override
>         public void onButtonClicked(View v, String action, FlyoutCategory category) {
>             // TODO (#503): Switch to using the view's tag to determine behavior
> ```

"view's tag" => "action string"

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/VariableCategory.java, line 32 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy32HyWQDCtXPGpUzV:-Kcy32HyWQDCtXPGpUzW:bcjqpln) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/android/control/VariableCategory.java#L32)):*
> ```Java
>  * Automatically adds/removes blocks from the category when the list of variables changes.
>  */
> public class VariableCategory extends FlyoutCategory {
> ```

See VariableFlyoutFactory comments.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryTabs.java, line 316 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy6Dqgryez3mciEuXu:-Kcy6Dqgryez3mciEuXv:b-enrvt9) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryTabs.java#L316)):*
> ```Java
>      * Callback for when the user clicks on a category.
>      */
>     public abstract static class Callback {
> ```

Search isn't finding any other instance of "onCategoryClicked" or "CategoryTabs.Callback". Is this used?

---

*[blocklylib-core/src/main/java/com/google/blockly/model/CategoryFactory.java, line 29 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy29NrlLRzEt4AvEmm:-Kcy29NrlLRzEt4AvEmn:baviufm) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/model/CategoryFactory.java#L29)):*
> ```Java
>     public abstract FlyoutCategory obtainFlyout(String customType);
> 
>     public static final class VariableFlyoutFactory extends CategoryFactory {
> ```

Rename VariableCategoryFactory.

It seems like everything in VariableCategory could be put here.  It doesn't seem to me like we should expect developers to extend two classes, and extending the data structure (FlyoutCategory) doesn't seem right.

In which case, it would become large enough to be  top level class.

Also, was "final" intentional? Not that I see a reason to extend this class. I'm okay with it if it was intentional.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/FlyoutCategory.java, line 321 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy6dNu-lxPWhhpITTH:-Kcy6dNu-lxPWhhpITTI:balt43y) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/model/FlyoutCategory.java#L321)):*
> ```Java
>      * Wraps items that can be displayed as part of a {@link FlyoutCategory}.
>      */
>     public abstract static class FlyoutItem {
> ```

CategoryItem?  (Flyout implies a particular drawer-like UI to me)

---

*[blocklylib-core/src/main/java/com/google/blockly/model/FlyoutCategory.java, line 359 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy3ZtCGq0NQbFpQlUX:-Kcy3ZtCGq0NQbFpQlUY:bsnzvu6) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/model/FlyoutCategory.java#L359)):*
> ```Java
>     /**
>      * Flyout item representing a clickable button, such as "Add Variable".
>      * TODO (#503): Support style and callback spec
> ```

I think the style spec was web/CSS specific. Hence "web-class". (For all of the discussions, why didn't we choose css-class?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/523)*

**Comment by RoboErikG** [comment]
Review status: 16 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/control/FlyoutController.java, line 63 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy1P2GCl0RCbyuxivf:-KcyOU9puQgjmG2ROWeE:bss4a2b) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/android/control/FlyoutController.java#L63)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

"view's tag" => "action string"
</blockquote></details>

Removed.

---

*[blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryTabs.java, line 316 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy6Dqgryez3mciEuXu:-KcyOxqMXVVZqojKoUG7:b-896fix) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/android/ui/CategoryTabs.java#L316)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Search isn't finding any other instance of "onCategoryClicked" or "CategoryTabs.Callback". Is this used?
</blockquote></details>

Done.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/CategoryFactory.java, line 29 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy29NrlLRzEt4AvEmm:-KcyPUY7IIyX3Th_ORZv:b-baxopq) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/model/CategoryFactory.java#L29)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

Rename VariableCategoryFactory.

It seems like everything in VariableCategory could be put here.  It doesn't seem to me like we should expect developers to extend two classes, and extending the data structure (FlyoutCategory) doesn't seem right.

In which case, it would become large enough to be  top level class.

Also, was "final" intentional? Not that I see a reason to extend this class. I'm okay with it if it was intentional.
</blockquote></details>

I'm not sure I understand how it would work as a single class. You still need a generic method to build new instances of the category, which can't be a static method because it may need additional information depending on implementation. Also, the category itself can be dynamic, so the list of items can't just be set at creation.

I could conceivably make CategoryFactory an interface that VariableCategory implements with obtainCategory just returning itself, but in general I can't assume the factory doesn't return a unique instance for each obtain call.

Making it final was intentional. It's a simple enough class I wanted to be clear this is a default implementation and devs should just create their own to replace it.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/FlyoutCategory.java, line 321 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy6dNu-lxPWhhpITTH:-KcyRhB-kZbanhA3jwwj:bhnmju0) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/model/FlyoutCategory.java#L321)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

CategoryItem?  (Flyout implies a particular drawer-like UI to me)
</blockquote></details>

I also renamed the top level class to BlocklyCategory

---

*[blocklylib-core/src/main/java/com/google/blockly/model/FlyoutCategory.java, line 359 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy3ZtCGq0NQbFpQlUX:-KcyRuQV1b0wWIBDgjBS:bvuizqt) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/model/FlyoutCategory.java#L359)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I think the style spec was web/CSS specific. Hence "web-class". (For all of the discussions, why didn't we choose css-class?).
</blockquote></details>

I think css-class was too confusing. I still need to add support for buttons in XML and their action tag and eventually some form of styling.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/523)*

**Comment by AnmAtAnm** [comment]
Reviewed 5 of 15 files at r3.
Review status: 16 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/CategoryFactory.java, line 29 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy29NrlLRzEt4AvEmm:-KcydgCUfHCkinZGzmeI:btupmf) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/model/CategoryFactory.java#L29)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

I'm not sure I understand how it would work as a single class. You still need a generic method to build new instances of the category, which can't be a static method because it may need additional information depending on implementation. Also, the category itself can be dynamic, so the list of items can't just be set at creation.

I could conceivably make CategoryFactory an interface that VariableCategory implements with obtainCategory just returning itself, but in general I can't assume the factory doesn't return a unique instance for each obtain call.

Making it final was intentional. It's a simple enough class I wanted to be clear this is a default implementation and devs should just create their own to replace it.
</blockquote></details>

I'm not grasping your usage of "generic method".

I imagine a single factory object for each custom string will be created, and the factory will create an instance (either once, or on demand) of the category's contents. The DatasetObserver for the variables can be registered during that creation, and update the category, as long as methods are added to modify the category, so I don't see that as a barrier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/523)*

**Comment by AnmAtAnm** [comment]
There is enough good stuff here, if you want to commit and iterate later.  Let me know if you have further questions about the factory.

---

Review status: 16 of 25 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/523#-:-Kcyfmrt3nDD6kIiDkxc:b84d69g)*

**Comment by RoboErikG** [comment]
Oh, I see what you mean! I'll do a followup change for that so I can reduce the merge noise.

---

Review status: 16 of 25 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/523#-:-KcymR7Eg8OYp_2NNEVm:b-qx8xp9)*

**Comment by RoboErikG** [comment]
Review status: 16 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[blocklylib-core/src/main/java/com/google/blockly/model/CategoryFactory.java, line 29 at r2](https://reviewable.io:443/reviews/google/blockly-android/523#-Kcy29NrlLRzEt4AvEmm:-Kcymd6quFMzb35Jkz6o:bw837qp) ([raw file](https://github.com/google/blockly-android/blob/e0805e3ea3c5edbe1e1554dc326df700324a9afd/blocklylib-core/src/main/java/com/google/blockly/model/CategoryFactory.java#L29)):*
<details><summary><i>Previously, AnmAtAnm (Andrew n marshall) wrote…</i></summary><blockquote>

I'm not grasping your usage of "generic method".

I imagine a single factory object for each custom string will be created, and the factory will create an instance (either once, or on demand) of the category's contents. The DatasetObserver for the variables can be registered during that creation, and update the category, as long as methods are added to modify the category, so I don't see that as a barrier.
</blockquote></details>

I understand now. Will followup with another CL to make this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/523)*

**Pull request merged**
