### PR TITLE
colour_*, text_* blocks except text_join (mutator)

### PR DESCRIPTION
**Pull request by AnmAtAnm**
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/395)

### CODE REVIEW

**Comment by AnmAtAnm** [comment]
PTAL +@roboerikg 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/395#-:-KTLgvl4POnhvpHNw-oS:b-l80uy5)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/395#-:-KTLtZ51xiymkkRJY0QK:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
New color files.
+@roboerikg  LG again?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/395#-:-KTQPc21QvIZ_JPdGbei:b-2bj3pg)*

**Comment by RoboErikG** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/395#-:-KTQS1gNYZLfgzGsoXKI:bnfp4nl)*

**Pull request merged**
