### PR TITLE
Adds audio files and polyphonic audio player to the CodeLab starter.

### PR DESCRIPTION
**Pull request by AnmAtAnm**
Adds audio files and polyphonic audio player (i.e., multiple files played at the same time).

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/634)

### CODE REVIEW

**Comment by RoboErikG** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[Codelab/codelab-starter/src/main/java/com/google/blockly/codelab/AudioFilePlayer.java, line 119 at r1](https://reviewable.io:443/reviews/google/blockly-android/634#-KpqEcC9nGx2dM6eqOBx:-KpqEcC9nGx2dM6eqOBy:b-pgl8v5) ([raw file](https://github.com/google/blockly-android/blob/7eb14efce132d32cb224d78b69591e09802aad07/Codelab/codelab-starter/src/main/java/com/google/blockly/codelab/AudioFilePlayer.java#L119)):*
> ```Java
>      */
>     private void findOrCreatePlayer(
>             final String filename, @Nullable final MediaPlayer.OnPreparedListener callback)
> ```

callback should be @NonNull since there's no other way to get a reference to the MediaPlayer that was returned.

---

*[Codelab/codelab-starter/src/main/java/com/google/blockly/codelab/AudioFilePlayer.java, line 128 at r1](https://reviewable.io:443/reviews/google/blockly-android/634#-KpqD6PvjjJDtW1Mo9TL:-KpqD6PvjjJDtW1Mo9TM:bdev9ph) ([raw file](https://github.com/google/blockly-android/blob/7eb14efce132d32cb224d78b69591e09802aad07/Codelab/codelab-starter/src/main/java/com/google/blockly/codelab/AudioFilePlayer.java#L128)):*
> ```Java
> 
>         if (list.isEmpty()) {
>             MediaPlayer player = new MediaPlayer();
> ```

You're missing an error listener. You might also be interested in a MediaPlayerManager class I wrote a while back if you're using MediaPlayer. https://googleplex-android-review.git.corp.google.com/#/c/324160/3/Tuq/src/com/google/android/aah/tuq/player/MediaPlayerManager.java

A better option might be to use SoundPool since you're playing multiple short sounds. https://developer.android.com/reference/android/media/SoundPool.html

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/634)*

**Comment by AnmAtAnm** [comment]
PTAL
Completely rewrite to be based off of SoundPool.  No longer has errors.

**Comment by RoboErikG** [comment]
:lgtm_strong:  One nit

---

Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[Codelab/codelab-starter/src/main/java/com/google/blockly/codelab/MultiFileAudioPlayer.java, line 50 at r2](https://reviewable.io:443/reviews/google/blockly-android/634#-KqO_88iWOCLZn1ClSon:-KqO_88iWOCLZn1ClSoo:b-6tc6m9) ([raw file](https://github.com/google/blockly-android/blob/1d2c399c1aa11d4a5d91a64b35e56c58427ab657/Codelab/codelab-starter/src/main/java/com/google/blockly/codelab/MultiFileAudioPlayer.java#L50)):*
> ```Java
>         mSoundPool = new SoundPool.Builder()
>                 .setAudioAttributes(audioAttrs)
>                 .setMaxStreams(9)  // One per button
> ```

Since you're overlapping notes I think you want this to be two per button for the worst case that won't really happen. ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/634#-:-KqOaH_xvq5l36W0nRCI:b-xgcpny)*

**Comment by AnmAtAnm** [comment]
Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[Codelab/codelab-starter/src/main/java/com/google/blockly/codelab/MultiFileAudioPlayer.java, line 50 at r2](https://reviewable.io:443/reviews/google/blockly-android/634#-KqO_88iWOCLZn1ClSon:-KqPb8LOy8mbLNbmBMGY:b-k2rwtz) ([raw file](https://github.com/google/blockly-android/blob/1d2c399c1aa11d4a5d91a64b35e56c58427ab657/Codelab/codelab-starter/src/main/java/com/google/blockly/codelab/MultiFileAudioPlayer.java#L50)):*
<details><summary><i>Previously, RoboErikG wrote…</i></summary><blockquote>

Since you're overlapping notes I think you want this to be two per button for the worst case that won't really happen. ;)
</blockquote></details>

Good catch. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/634)*

**Pull request merged**
