### PR TITLE
Adding support from "style" blocks and "hat": "cap"

### PR DESCRIPTION
**Pull request by AnmAtAnm**
The PatchManager now loads both the default top-left path and the
hat patch into memory, since they can both be in use in the same workspace..

Added a test block to the DevTest toolbox and workspace.

---
This change is [Reviewable](https://reviewable.io/reviews/google/blockly-android/682)

### CODE REVIEW

**Comment by rachel-fenichel** [comment]
Reviewed 8 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/InputView.java, line 86 at r1](https://reviewable.io:443/reviews/google/blockly-android/682#-KxKjZVOIilz_ukKGYF2:-KxKjZVPF-oLQnW0y1MJ:b-9x7s49) ([raw file](https://github.com/google/blockly-android/blob/91eb2ebef02de4081a51b08945d87bbe3b2e22bb/blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/InputView.java#L86)):*
> ```Java
>         }
>         mHasMeasuredFieldsAndInput = false;
>         BlockGroup connectedBlockGroup = getConnectedBlockGroup();
> ```

Why did this become a block group?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/682)*

**Comment by AnmAtAnm** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/InputView.java, line 86 at r1](https://reviewable.io:443/reviews/google/blockly-android/682#-KxKjZVOIilz_ukKGYF2:-KxKl3Om5h6ri0tv2nRI:b-yeuhzd) ([raw file](https://github.com/google/blockly-android/blob/91eb2ebef02de4081a51b08945d87bbe3b2e22bb/blocklylib-vertical/src/main/java/com/google/blockly/android/ui/vertical/InputView.java#L86)):*
<details><summary><i>Previously, rachel-fenichel (Rachel Fenichel) wrote…</i></summary><blockquote>

Why did this become a block group?
</blockquote></details>

The only use of the previous block was to pass it into the PatchManager's helper function. But now that hats are per-block and specific to the BlockView implementation, I pass in a view. However, there was a case where the input did not have a block, so it was easier to pass in the whole group, offloading a lot of ugly null check and similar logic to the helper function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/682)*

**Comment by rachel-fenichel** [comment]
:lgtm:

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/blockly-android/682#-:-KxKlmhWsa8vtbLm4nYp:bnfp4nl)*

**Comment by AnmAtAnm** [comment]
Resolves #659

**Pull request merged**
